import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";

const nav = [["Home","home"],["Expertise","expertise"],["Experience","experience"],["Portfolio","portfolio"],["Contact","contact"]];
const socials = [
  ["in","https://www.linkedin.com/feed/","LinkedIn"],
  ["gh","https://github.com/mahadihasan999","GitHub"],
  ["f","https://www.facebook.com/er.mahadihasan","Facebook"]
];
const metrics = [["80k+","Leads Generated"],["8x","Average ROAS"],["17x","Maximum ROAS"],["5M+","Revenue"]];
const capabilities = [
  ["01","Digital Marketing",["Facebook / Google Ads","TikTok / YouTube Ads","YouTube SEO","CRO Strategy","Strategy Planning"]],
  ["02","Development",["React.js","Node.js","Laravel","MySQL","MongoDB","Tailwind CSS"]],
  ["03","IT & Security",["Cyber Security","Information Security Analyst","Server Management","3CX Systems","Call Center Ops"]],
  ["04","Creative",["Copywriting","Visual Direction","Figma","Brand Design"]]
];
const projects = [
  {title:"Barz App",type:"Productivity",desc:"A creative productivity tool for songwriters to find end rhyming words, calculate syllable counts, and improve lyrical flow.",tags:["React","API Integration"],url:"https://barz-app-pro.web.app/",image:"https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?auto=format&fit=crop&q=80&w=1000"},
  {title:"Maliha Tabassum",type:"Blog & E-com",desc:"An elegant online blog and book-selling web application with a custom CMS, reading mode, and integrated e-commerce.",tags:["React","Node.js"],url:"https://malihatabassum.com/",image:"https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=1000"},
  {title:"Integmeds POS",type:"Management",desc:"Advanced point of sale software for medical and retail inventory management with real-time sales tracking and reporting.",tags:["Laravel","Vue.js"],url:"https://integmeds.doxix.online/",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1000"},
  {title:"FA E-commerce",type:"E-commerce",desc:"A high-performance e-commerce platform focused on smooth user experience and secure transactions.",tags:["React","Node.js"],url:"https://fa.doxix.online/",image:"https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&q=80&w=1000"},
  {title:"NY Integrated Wellness",type:"Health",desc:"Professional clinic website with appointment scheduling and patient resource management.",tags:["Next.js","Tailwind"],url:"https://nyintegratwellness.com/",image:"https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=1000"},
  {title:"Home Pros",type:"Real Estate",desc:"A comprehensive real estate platform for browsing homes, contacting agents, and efficiently managing property details.",tags:["React.js","Tailwind"],url:"https://home-pros-theta.vercel.app/",image:"https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1000"}
];

function Arrow(){ return <span aria-hidden="true">↗</span> }
function Header(){
  const [open,setOpen]=useState(false);
  return <header className="fixed inset-x-0 top-0 z-50 px-4 pt-4">
    <div className="mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/10 bg-ink/75 px-4 py-3 shadow-2xl backdrop-blur-xl sm:px-6">
      <a href="#home" className="flex items-center gap-3 font-display text-lg font-bold text-white"><b className="grid h-9 w-9 place-items-center rounded-xl bg-electric text-xs">MH</b>Mahadi<span className="text-electric">.</span></a>
      <nav className="hidden items-center gap-7 md:flex">{nav.map(([n,id])=><a key={id} className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400 transition hover:text-white" href={`#${id}`}>{n}</a>)}</nav>
      <a className="hidden rounded-full border border-white/15 px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-white sm:block" href="mailto:contact@mahadi.bd">Let's talk</a>
      <button onClick={()=>setOpen(!open)} className="grid h-9 w-9 place-items-center rounded-full border border-white/15 md:hidden" aria-label="Toggle menu">☰</button>
    </div>
    {open&&<nav className="mx-auto mt-2 grid max-w-7xl rounded-3xl border border-white/10 bg-ink/95 p-5 backdrop-blur-xl md:hidden">{nav.map(([n,id])=><a onClick={()=>setOpen(false)} key={id} className="border-b border-white/10 py-3 text-sm font-bold" href={`#${id}`}>{n}</a>)}</nav>}
  </header>
}

function Hero(){
  const roles=["Head of Digital Marketing","Full Stack Developer","Multi-departmental IT Manager"];
  const [role,setRole]=useState(0);
  useEffect(()=>{const id=setInterval(()=>setRole(r=>(r+1)%roles.length),2300);return()=>clearInterval(id)},[]);
  return <section id="home" className="grid-bg relative min-h-screen overflow-hidden pt-28">
    <div className="blue-glow absolute -right-48 -top-48 h-[650px] w-[650px]"/>
    <div className="shell grid min-h-[calc(100vh-7rem)] items-center gap-14 pb-16 lg:grid-cols-[1.1fr_.9fr]">
      <div className="relative z-10">
        <p className="mb-7 inline-flex items-center gap-2 rounded-full border border-electric/25 bg-electric/10 px-4 py-2 text-[9px] font-extrabold uppercase tracking-[.18em] text-blue-300"><i className="h-1.5 w-1.5 rounded-full bg-cyan shadow-[0_0_12px_#26d9e8]"/>Open for Strategic Partnerships</p>
        <h1 className="font-display text-[clamp(4.5rem,10vw,9rem)] font-bold leading-[.78] tracking-[-.09em] text-white">Mahadi<br/><span className="text-transparent [-webkit-text-stroke:1px_#667085]">Hasan</span></h1>
        <div className="mt-8 flex items-center gap-4"><span className="h-px w-10 bg-electric"/><p className="font-display text-lg font-semibold text-cyan sm:text-2xl">{roles[role]}</p></div>
        <p className="mt-7 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">Multi-departmental IT Manager and Digital Marketing Strategist with 8+ years of experience leading cross-functional teams. Specialized in driving multimillion-dollar revenue through data-driven marketing and robust technology integration.</p>
        <div className="mt-9 flex flex-wrap items-center gap-4"><a className="btn-primary" href="#portfolio">View portfolio <Arrow/></a><a className="btn-ghost" href="#contact">Start a conversation</a></div>
        <div className="mt-9 flex gap-3">{socials.map(([short,url,label])=><a key={label} target="_blank" rel="noreferrer" aria-label={label} href={url} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-[10px] font-bold uppercase text-slate-400 transition hover:border-electric hover:text-white">{short}</a>)}</div>
      </div>
      <div className="relative mx-auto w-full max-w-md lg:ml-auto">
        <div className="absolute -inset-6 rounded-[4rem] border border-electric/20"/><div className="absolute -inset-12 rounded-[5rem] border border-white/5"/>
        <div className="relative aspect-[4/5] overflow-hidden rounded-[3.2rem] border border-white/15 bg-panel shadow-[0_30px_100px_rgba(0,0,0,.5)]"><img className="h-full w-full object-cover" src="https://i.ibb.co.com/6JnGsScC/IMG-4909-1.jpg" alt="Mahadi Hasan"/></div>
        <div className="glass animate-float absolute -bottom-7 -left-4 rounded-2xl px-5 py-4 shadow-xl"><p className="text-[9px] uppercase tracking-widest text-slate-400">Based in</p><p className="mt-1 text-xs font-bold text-white">Dhaka, Bangladesh</p></div>
        <div className="glass absolute -right-4 top-12 rounded-2xl px-5 py-4 shadow-xl"><p className="text-[9px] uppercase tracking-widest text-slate-400">Average ROAS</p><p className="font-display text-3xl font-bold text-cyan">8X</p></div>
      </div>
    </div>
  </section>
}

function Metrics(){return <section className="border-y border-white/10 bg-panel"><div className="shell grid grid-cols-2 divide-x divide-white/10 lg:grid-cols-4">{metrics.map(([num,label])=><div key={label} className="px-5 py-10 sm:p-10"><h3 className="font-display text-4xl font-bold tracking-tight text-white sm:text-5xl">{num}</h3><p className="mt-2 text-[9px] font-bold uppercase tracking-[.18em] text-slate-500">{label}</p></div>)}</div></section>}
function Expertise(){return <section id="expertise" className="section shell"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="label">Capabilities</p><h2 className="section-title">Expertise<br/><span className="text-slate-600">&amp; tools.</span></h2><p className="mt-7 max-w-sm text-sm leading-7 text-slate-500">A multidisciplinary toolkit spanning growth strategy, software development, infrastructure, and creative direction.</p></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map(([n,title,items])=><article key={title} className="glass group rounded-3xl p-7 transition hover:-translate-y-1 hover:border-electric/40"><span className="text-[9px] font-bold tracking-widest text-electric">{n}</span><h3 className="mt-8 font-display text-2xl font-bold text-white">{title}</h3><div className="mt-6 flex flex-wrap gap-2">{items.map(i=><span className="tag" key={i}>{i}</span>)}</div></article>)}</div></div></section>}
function Experience(){return <section id="experience" className="section border-y border-white/10 bg-panel"><div className="shell grid gap-16 lg:grid-cols-[.7fr_1.3fr]"><div><p className="label">Experience</p><h2 className="section-title">Professional<br/><span className="text-slate-600">milestones.</span></h2></div><div className="timeline relative space-y-14 pl-10"><ExperienceItem date="2021 — Present" title="Manager — IT & Digital Marketing" company="American Wellness Center (Dhaka, Texas, New York)" tags={["Ads Management","SEO","CRO","Strategy"]} intro="Leading global digital marketing initiatives and strategy planning for high-growth health centers." bullets={["Generated over 80k+ Leads & Multimillion Dollar Revenue","Orchestrated end-to-end Strategy Planning for international markets","Managed high-budget Facebook, Google, TikTok, and YouTube Ad campaigns","Optimized YouTube SEO & Conversion Rate Optimization (CRO)","Led cross-functional Copywriting & Visual teams for creative production","Achieved an average 8X ROAS (17x Max) for the company"]}/><ExperienceItem date="2019 — 2021" title="Senior Full Stack Developer" company="Freelance & Marketplaces" tags={["Node.js","React.js","MySQL"]} intro="Delivered 50+ projects across various industries. Developed end-to-end web apps using MERN stack and Laravel." bullets={["Built custom CRM solutions for small businesses","Optimized database performance for high-traffic sites","Integrated multiple third-party APIs and payment gateways"]}/></div></div></section>}
function ExperienceItem({date,title,company,tags,intro,bullets}){return <article className="relative"><i className="absolute -left-[39px] top-2 h-4 w-4 rounded-full border-4 border-panel bg-electric shadow-[0_0_16px_#1678ff]"/><p className="text-[9px] font-extrabold uppercase tracking-[.2em] text-cyan">{date}</p><h3 className="mt-3 font-display text-2xl font-bold text-white sm:text-3xl">{title}</h3><p className="mt-2 text-xs font-semibold text-electric">{company}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><p className="mt-6 max-w-2xl text-sm leading-7 text-slate-400">{intro}</p><ul className="mt-5 grid gap-3 text-xs text-slate-500">{bullets.map(b=><li key={b} className="flex gap-3 before:mt-1.5 before:h-1 before:w-1 before:shrink-0 before:rounded-full before:bg-cyan">{b}</li>)}</ul></article>}
function Portfolio(){return <section id="portfolio" className="section shell"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="label">Portfolio</p><h2 className="section-title">Featured<br/><span className="text-slate-600">projects.</span></h2></div><p className="max-w-sm text-sm leading-7 text-slate-500">Selected products and platforms built across productivity, healthcare, retail, and real estate.</p></div><div className="mt-16 grid gap-6 md:grid-cols-2">{projects.map((p,i)=><a className={`project-card glass group overflow-hidden rounded-[2rem] ${i===0||i===5?"md:col-span-2":""}`} target="_blank" rel="noreferrer" href={p.url} key={p.title}><div className={`${i===0||i===5?"aspect-[16/7]":"aspect-[16/10]"} overflow-hidden`}><img className="h-full w-full object-cover opacity-65 transition duration-700" src={p.image} alt={p.title}/></div><div className="p-7 sm:p-8"><div className="flex items-start justify-between gap-5"><div><span className="text-[9px] font-extrabold uppercase tracking-[.2em] text-cyan">{p.type}</span><h3 className="mt-2 font-display text-2xl font-bold text-white sm:text-3xl">{p.title}</h3></div><span className="project-arrow grid h-11 w-11 shrink-0 place-items-center rounded-full border border-white/15 transition duration-300"><Arrow/></span></div><p className="mt-4 max-w-xl text-xs leading-6 text-slate-500">{p.desc}</p><div className="mt-5 flex gap-2">{p.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div></div></a>)}</div></section>}
function Contact(){return <section id="contact" className="relative overflow-hidden border-t border-white/10 bg-panel py-24 sm:py-32"><div className="blue-glow absolute -bottom-72 left-1/2 h-[650px] w-[650px] -translate-x-1/2"/><div className="shell relative text-center"><p className="label justify-center before:hidden">Start a conversation</p><h2 className="font-display text-5xl font-bold tracking-[-.06em] text-white sm:text-7xl lg:text-8xl">Let's connect<span className="text-electric">.</span></h2><p className="mx-auto mt-6 max-w-lg text-sm leading-7 text-slate-400">Have a strategic partnership, marketing challenge, or product idea? Let's talk about how technology and data can move it forward.</p><a href="mailto:contact@mahadi.bd" className="mt-10 inline-block font-display text-2xl font-bold text-cyan underline decoration-white/20 underline-offset-8 sm:text-4xl">contact@mahadi.bd</a><div className="mt-9 flex flex-wrap justify-center gap-3"><a className="btn-primary" href="https://wa.me/8801785083768" target="_blank" rel="noreferrer">WhatsApp: +8801785083768 <Arrow/></a>{socials.map(([short,url,label])=><a key={label} className="btn-ghost" href={url} target="_blank" rel="noreferrer">{label}</a>)}</div></div></section>}
function Footer(){return <footer className="border-t border-white/10 py-7"><div className="shell flex flex-col justify-between gap-3 text-[9px] font-bold uppercase tracking-[.14em] text-slate-600 sm:flex-row"><span>© 2026 Mahadi Hasan. Crafted with precision.</span><a href="#home">Back to top ↑</a></div></footer>}
function App(){return <><Header/><main><Hero/><Metrics/><Expertise/><Experience/><Portfolio/><Contact/></main><Footer/><a aria-label="Contact on WhatsApp" className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-emerald-500 font-bold text-white shadow-[0_15px_35px_rgba(16,185,129,.35)] transition hover:-translate-y-1" href="https://wa.me/8801785083768" target="_blank" rel="noreferrer">WA</a></>}

createRoot(document.getElementById("root")).render(<App />);
